name: ci

on: push
jobs:
    build-and-test: 
        runs-on: ubuntu-latest
        steps:
          - name: Download the repository
            uses: actions/checkout@v4
          
          - name: Install Python
            uses: actions/setup-python@v5
            with:
              python-version: 3.11.5
          
          - name: Install Poetry
            run: pip install poetry

          - name: Install dependencies with Poetry
            run: poetry install

          - name: Run automated tests with Poetry
            run: poetry run pytest tests -v